plugins { id 'java' }
repositories { mavenCentral() }
dependencies { testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2' }
test { useJUnitPlatform() }
java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
tasks.withType(Test) { systemProperty 'file.encoding', 'UTF-8' }
